services:

  postgres:
    image: postgres:16
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
